### ISSUE TITLE
Error messages are not displayed with 'screenshotsOnlyOnFailure: false'

### ISSUE THREAD

**Issue by devtrove** [etxebe/protractor-html-reporter#2]
To reproduce:
1. Set "screenshotsOnlyOnFailure: false"
2. Run test case which fails

**Problem:** no error messages are displayed in HTML report. Only screenshot.

Error message is displayed when "screenshotsOnlyOnFailure: true" is set.

**Comment by etxebe** [comment]
Thanks for spotting this. I have already added your fix to my version. Thanks :)
